<?php

/**
 * Base class that represents a row from the 'distancejob' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 30 15:27:45 2012
 *
 * @package    lib.model.smafe.om
 */
abstract class BaseDistancejob extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        DistancejobPeer
	 */
	protected static $peer;

	/**
	 * The value for the featurevectortype_id field.
	 * @var        int
	 */
	protected $featurevectortype_id;

	/**
	 * The value for the track_id field.
	 * @var        int
	 */
	protected $track_id;

	/**
	 * The value for the distancetype_id field.
	 * @var        int
	 */
	protected $distancetype_id;

	/**
	 * The value for the smafejob_addfile_id field.
	 * @var        int
	 */
	protected $smafejob_addfile_id;

	/**
	 * The value for the status field.
	 * @var        string
	 */
	protected $status;

	/**
	 * The value for the priority field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $priority;

	/**
	 * The value for the created field.
	 * Note: this column has a database default value of: '-99999--99999--99999T-99999:-99999:-99999+0000'
	 * @var        string
	 */
	protected $created;

	/**
	 * The value for the started field.
	 * @var        string
	 */
	protected $started;

	/**
	 * The value for the finished field.
	 * @var        string
	 */
	protected $finished;

	/**
	 * @var        Featurevector
	 */
	protected $aFeaturevector;

	/**
	 * @var        Distancetype
	 */
	protected $aDistancetype;

	/**
	 * @var        SmafejobAddfile
	 */
	protected $aSmafejobAddfile;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'DistancejobPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->priority = 0;
		$this->created = '-99999--99999--99999T-99999:-99999:-99999+0000';
	}

	/**
	 * Initializes internal state of BaseDistancejob object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [featurevectortype_id] column value.
	 * 
	 * @return     int
	 */
	public function getFeaturevectortypeId()
	{
		return $this->featurevectortype_id;
	}

	/**
	 * Get the [track_id] column value.
	 * 
	 * @return     int
	 */
	public function getTrackId()
	{
		return $this->track_id;
	}

	/**
	 * Get the [distancetype_id] column value.
	 * 
	 * @return     int
	 */
	public function getDistancetypeId()
	{
		return $this->distancetype_id;
	}

	/**
	 * Get the [smafejob_addfile_id] column value.
	 * 
	 * @return     int
	 */
	public function getSmafejobAddfileId()
	{
		return $this->smafejob_addfile_id;
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     string
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [priority] column value.
	 * 
	 * @return     int
	 */
	public function getPriority()
	{
		return $this->priority;
	}

	/**
	 * Get the [optionally formatted] temporal [created] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreated($format = 'Y-m-d H:i:s')
	{
		if ($this->created === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [started] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getStarted($format = 'Y-m-d H:i:s')
	{
		if ($this->started === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->started);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->started, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [finished] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFinished($format = 'Y-m-d H:i:s')
	{
		if ($this->finished === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->finished);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->finished, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [featurevectortype_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Distancejob The current object (for fluent API support)
	 */
	public function setFeaturevectortypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->featurevectortype_id !== $v) {
			$this->featurevectortype_id = $v;
			$this->modifiedColumns[] = DistancejobPeer::FEATUREVECTORTYPE_ID;
		}

		return $this;
	} // setFeaturevectortypeId()

	/**
	 * Set the value of [track_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Distancejob The current object (for fluent API support)
	 */
	public function setTrackId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->track_id !== $v) {
			$this->track_id = $v;
			$this->modifiedColumns[] = DistancejobPeer::TRACK_ID;
		}

		if ($this->aFeaturevector !== null && $this->aFeaturevector->getTrackId() !== $v) {
			$this->aFeaturevector = null;
		}

		return $this;
	} // setTrackId()

	/**
	 * Set the value of [distancetype_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Distancejob The current object (for fluent API support)
	 */
	public function setDistancetypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->distancetype_id !== $v) {
			$this->distancetype_id = $v;
			$this->modifiedColumns[] = DistancejobPeer::DISTANCETYPE_ID;
		}

		if ($this->aDistancetype !== null && $this->aDistancetype->getId() !== $v) {
			$this->aDistancetype = null;
		}

		return $this;
	} // setDistancetypeId()

	/**
	 * Set the value of [smafejob_addfile_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Distancejob The current object (for fluent API support)
	 */
	public function setSmafejobAddfileId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->smafejob_addfile_id !== $v) {
			$this->smafejob_addfile_id = $v;
			$this->modifiedColumns[] = DistancejobPeer::SMAFEJOB_ADDFILE_ID;
		}

		if ($this->aSmafejobAddfile !== null && $this->aSmafejobAddfile->getId() !== $v) {
			$this->aSmafejobAddfile = null;
		}

		return $this;
	} // setSmafejobAddfileId()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      string $v new value
	 * @return     Distancejob The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->status !== $v) {
			$this->status = $v;
			$this->modifiedColumns[] = DistancejobPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Set the value of [priority] column.
	 * 
	 * @param      int $v new value
	 * @return     Distancejob The current object (for fluent API support)
	 */
	public function setPriority($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->priority !== $v || $this->isNew()) {
			$this->priority = $v;
			$this->modifiedColumns[] = DistancejobPeer::PRIORITY;
		}

		return $this;
	} // setPriority()

	/**
	 * Sets the value of [created] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Distancejob The current object (for fluent API support)
	 */
	public function setCreated($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created !== null && $tmpDt = new DateTime($this->created)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					|| ($dt->format('Y-m-d\\TH:i:sO') === '-99999--99999--99999T-99999:-99999:-99999+0000') // or the entered value matches the default
					)
			{
				$this->created = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = DistancejobPeer::CREATED;
			}
		} // if either are not null

		return $this;
	} // setCreated()

	/**
	 * Sets the value of [started] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Distancejob The current object (for fluent API support)
	 */
	public function setStarted($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->started !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->started !== null && $tmpDt = new DateTime($this->started)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->started = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = DistancejobPeer::STARTED;
			}
		} // if either are not null

		return $this;
	} // setStarted()

	/**
	 * Sets the value of [finished] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Distancejob The current object (for fluent API support)
	 */
	public function setFinished($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->finished !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->finished !== null && $tmpDt = new DateTime($this->finished)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->finished = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = DistancejobPeer::FINISHED;
			}
		} // if either are not null

		return $this;
	} // setFinished()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->priority !== 0) {
				return false;
			}

			if ($this->created !== '-99999--99999--99999T-99999:-99999:-99999+0000') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->featurevectortype_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->track_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->distancetype_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->smafejob_addfile_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->status = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->priority = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->created = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->started = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->finished = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = DistancejobPeer::NUM_COLUMNS - DistancejobPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Distancejob object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aFeaturevector !== null && $this->track_id !== $this->aFeaturevector->getTrackId()) {
			$this->aFeaturevector = null;
		}
		if ($this->aDistancetype !== null && $this->distancetype_id !== $this->aDistancetype->getId()) {
			$this->aDistancetype = null;
		}
		if ($this->aSmafejobAddfile !== null && $this->smafejob_addfile_id !== $this->aSmafejobAddfile->getId()) {
			$this->aSmafejobAddfile = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DistancejobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = DistancejobPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aFeaturevector = null;
			$this->aDistancetype = null;
			$this->aSmafejobAddfile = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DistancejobPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseDistancejob:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				DistancejobPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseDistancejob:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DistancejobPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseDistancejob:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseDistancejob:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				DistancejobPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aFeaturevector !== null) {
				if ($this->aFeaturevector->isModified() || $this->aFeaturevector->isNew()) {
					$affectedRows += $this->aFeaturevector->save($con);
				}
				$this->setFeaturevector($this->aFeaturevector);
			}

			if ($this->aDistancetype !== null) {
				if ($this->aDistancetype->isModified() || $this->aDistancetype->isNew()) {
					$affectedRows += $this->aDistancetype->save($con);
				}
				$this->setDistancetype($this->aDistancetype);
			}

			if ($this->aSmafejobAddfile !== null) {
				if ($this->aSmafejobAddfile->isModified() || $this->aSmafejobAddfile->isNew()) {
					$affectedRows += $this->aSmafejobAddfile->save($con);
				}
				$this->setSmafejobAddfile($this->aSmafejobAddfile);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = DistancejobPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += DistancejobPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aFeaturevector !== null) {
				if (!$this->aFeaturevector->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aFeaturevector->getValidationFailures());
				}
			}

			if ($this->aDistancetype !== null) {
				if (!$this->aDistancetype->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aDistancetype->getValidationFailures());
				}
			}

			if ($this->aSmafejobAddfile !== null) {
				if (!$this->aSmafejobAddfile->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSmafejobAddfile->getValidationFailures());
				}
			}


			if (($retval = DistancejobPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = DistancejobPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getFeaturevectortypeId();
				break;
			case 1:
				return $this->getTrackId();
				break;
			case 2:
				return $this->getDistancetypeId();
				break;
			case 3:
				return $this->getSmafejobAddfileId();
				break;
			case 4:
				return $this->getStatus();
				break;
			case 5:
				return $this->getPriority();
				break;
			case 6:
				return $this->getCreated();
				break;
			case 7:
				return $this->getStarted();
				break;
			case 8:
				return $this->getFinished();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = DistancejobPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getFeaturevectortypeId(),
			$keys[1] => $this->getTrackId(),
			$keys[2] => $this->getDistancetypeId(),
			$keys[3] => $this->getSmafejobAddfileId(),
			$keys[4] => $this->getStatus(),
			$keys[5] => $this->getPriority(),
			$keys[6] => $this->getCreated(),
			$keys[7] => $this->getStarted(),
			$keys[8] => $this->getFinished(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = DistancejobPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setFeaturevectortypeId($value);
				break;
			case 1:
				$this->setTrackId($value);
				break;
			case 2:
				$this->setDistancetypeId($value);
				break;
			case 3:
				$this->setSmafejobAddfileId($value);
				break;
			case 4:
				$this->setStatus($value);
				break;
			case 5:
				$this->setPriority($value);
				break;
			case 6:
				$this->setCreated($value);
				break;
			case 7:
				$this->setStarted($value);
				break;
			case 8:
				$this->setFinished($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = DistancejobPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setFeaturevectortypeId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTrackId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDistancetypeId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setSmafejobAddfileId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setStatus($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPriority($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCreated($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setStarted($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFinished($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(DistancejobPeer::DATABASE_NAME);

		if ($this->isColumnModified(DistancejobPeer::FEATUREVECTORTYPE_ID)) $criteria->add(DistancejobPeer::FEATUREVECTORTYPE_ID, $this->featurevectortype_id);
		if ($this->isColumnModified(DistancejobPeer::TRACK_ID)) $criteria->add(DistancejobPeer::TRACK_ID, $this->track_id);
		if ($this->isColumnModified(DistancejobPeer::DISTANCETYPE_ID)) $criteria->add(DistancejobPeer::DISTANCETYPE_ID, $this->distancetype_id);
		if ($this->isColumnModified(DistancejobPeer::SMAFEJOB_ADDFILE_ID)) $criteria->add(DistancejobPeer::SMAFEJOB_ADDFILE_ID, $this->smafejob_addfile_id);
		if ($this->isColumnModified(DistancejobPeer::STATUS)) $criteria->add(DistancejobPeer::STATUS, $this->status);
		if ($this->isColumnModified(DistancejobPeer::PRIORITY)) $criteria->add(DistancejobPeer::PRIORITY, $this->priority);
		if ($this->isColumnModified(DistancejobPeer::CREATED)) $criteria->add(DistancejobPeer::CREATED, $this->created);
		if ($this->isColumnModified(DistancejobPeer::STARTED)) $criteria->add(DistancejobPeer::STARTED, $this->started);
		if ($this->isColumnModified(DistancejobPeer::FINISHED)) $criteria->add(DistancejobPeer::FINISHED, $this->finished);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(DistancejobPeer::DATABASE_NAME);

		$criteria->add(DistancejobPeer::FEATUREVECTORTYPE_ID, $this->featurevectortype_id);
		$criteria->add(DistancejobPeer::TRACK_ID, $this->track_id);
		$criteria->add(DistancejobPeer::DISTANCETYPE_ID, $this->distancetype_id);

		return $criteria;
	}

	/**
	 * Returns the composite primary key for this object.
	 * The array elements will be in same order as specified in XML.
	 * @return     array
	 */
	public function getPrimaryKey()
	{
		$pks = array();

		$pks[0] = $this->getFeaturevectortypeId();

		$pks[1] = $this->getTrackId();

		$pks[2] = $this->getDistancetypeId();

		return $pks;
	}

	/**
	 * Set the [composite] primary key.
	 *
	 * @param      array $keys The elements of the composite key (order must match the order in XML file).
	 * @return     void
	 */
	public function setPrimaryKey($keys)
	{

		$this->setFeaturevectortypeId($keys[0]);

		$this->setTrackId($keys[1]);

		$this->setDistancetypeId($keys[2]);

	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Distancejob (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFeaturevectortypeId($this->featurevectortype_id);

		$copyObj->setTrackId($this->track_id);

		$copyObj->setDistancetypeId($this->distancetype_id);

		$copyObj->setSmafejobAddfileId($this->smafejob_addfile_id);

		$copyObj->setStatus($this->status);

		$copyObj->setPriority($this->priority);

		$copyObj->setCreated($this->created);

		$copyObj->setStarted($this->started);

		$copyObj->setFinished($this->finished);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Distancejob Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     DistancejobPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new DistancejobPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Featurevector object.
	 *
	 * @param      Featurevector $v
	 * @return     Distancejob The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setFeaturevector(Featurevector $v = null)
	{
		if ($v === null) {
			$this->setTrackId(NULL);
		} else {
			$this->setTrackId($v->getTrackId());
		}

		$this->aFeaturevector = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Featurevector object, it will not be re-added.
		if ($v !== null) {
			$v->addDistancejob($this);
		}

		return $this;
	}


	/**
	 * Get the associated Featurevector object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Featurevector The associated Featurevector object.
	 * @throws     PropelException
	 */
	public function getFeaturevector(PropelPDO $con = null)
	{
		if ($this->aFeaturevector === null && ($this->track_id !== null)) {
			$this->aFeaturevector = FeaturevectorPeer::retrieveByPk($this->track_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aFeaturevector->addDistancejobs($this);
			 */
		}
		return $this->aFeaturevector;
	}

	/**
	 * Declares an association between this object and a Distancetype object.
	 *
	 * @param      Distancetype $v
	 * @return     Distancejob The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setDistancetype(Distancetype $v = null)
	{
		if ($v === null) {
			$this->setDistancetypeId(NULL);
		} else {
			$this->setDistancetypeId($v->getId());
		}

		$this->aDistancetype = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Distancetype object, it will not be re-added.
		if ($v !== null) {
			$v->addDistancejob($this);
		}

		return $this;
	}


	/**
	 * Get the associated Distancetype object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Distancetype The associated Distancetype object.
	 * @throws     PropelException
	 */
	public function getDistancetype(PropelPDO $con = null)
	{
		if ($this->aDistancetype === null && ($this->distancetype_id !== null)) {
			$this->aDistancetype = DistancetypePeer::retrieveByPk($this->distancetype_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aDistancetype->addDistancejobs($this);
			 */
		}
		return $this->aDistancetype;
	}

	/**
	 * Declares an association between this object and a SmafejobAddfile object.
	 *
	 * @param      SmafejobAddfile $v
	 * @return     Distancejob The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSmafejobAddfile(SmafejobAddfile $v = null)
	{
		if ($v === null) {
			$this->setSmafejobAddfileId(NULL);
		} else {
			$this->setSmafejobAddfileId($v->getId());
		}

		$this->aSmafejobAddfile = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SmafejobAddfile object, it will not be re-added.
		if ($v !== null) {
			$v->addDistancejob($this);
		}

		return $this;
	}


	/**
	 * Get the associated SmafejobAddfile object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SmafejobAddfile The associated SmafejobAddfile object.
	 * @throws     PropelException
	 */
	public function getSmafejobAddfile(PropelPDO $con = null)
	{
		if ($this->aSmafejobAddfile === null && ($this->smafejob_addfile_id !== null)) {
			$this->aSmafejobAddfile = SmafejobAddfilePeer::retrieveByPk($this->smafejob_addfile_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSmafejobAddfile->addDistancejobs($this);
			 */
		}
		return $this->aSmafejobAddfile;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aFeaturevector = null;
			$this->aDistancetype = null;
			$this->aSmafejobAddfile = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseDistancejob:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseDistancejob::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseDistancejob
