<?php

/**
 * Base class that represents a row from the 'smafejob_addfile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 30 15:27:45 2012
 *
 * @package    lib.model.smafe.om
 */
abstract class BaseSmafejobAddfile extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        SmafejobAddfilePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the priority field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $priority;

	/**
	 * The value for the file_uri field.
	 * @var        string
	 */
	protected $file_uri;

	/**
	 * The value for the created field.
	 * Note: this column has a database default value of: '-99999--99999--99999T-99999:-99999:-99999+0000'
	 * @var        string
	 */
	protected $created;

	/**
	 * The value for the started field.
	 * @var        string
	 */
	protected $started;

	/**
	 * The value for the finished1 field.
	 * @var        string
	 */
	protected $finished1;

	/**
	 * The value for the started2 field.
	 * @var        string
	 */
	protected $started2;

	/**
	 * The value for the finished2 field.
	 * @var        string
	 */
	protected $finished2;

	/**
	 * The value for the finished field.
	 * @var        string
	 */
	protected $finished;

	/**
	 * The value for the status field.
	 * @var        string
	 */
	protected $status;

	/**
	 * The value for the collection_name field.
	 * @var        string
	 */
	protected $collection_name;

	/**
	 * The value for the log field.
	 * @var        string
	 */
	protected $log;

	/**
	 * The value for the external_key field.
	 * @var        string
	 */
	protected $external_key;

	/**
	 * The value for the guid field.
	 * @var        string
	 */
	protected $guid;

	/**
	 * @var        array Distancejob[] Collection to store aggregation of Distancejob objects.
	 */
	protected $collDistancejobs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collDistancejobs.
	 */
	private $lastDistancejobCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'SmafejobAddfilePeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->priority = 0;
		$this->created = '-99999--99999--99999T-99999:-99999:-99999+0000';
	}

	/**
	 * Initializes internal state of BaseSmafejobAddfile object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [priority] column value.
	 * 
	 * @return     int
	 */
	public function getPriority()
	{
		return $this->priority;
	}

	/**
	 * Get the [file_uri] column value.
	 * 
	 * @return     string
	 */
	public function getFileUri()
	{
		return $this->file_uri;
	}

	/**
	 * Get the [optionally formatted] temporal [created] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreated($format = 'Y-m-d H:i:s')
	{
		if ($this->created === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [started] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getStarted($format = 'Y-m-d H:i:s')
	{
		if ($this->started === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->started);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->started, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [finished1] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFinished1($format = 'Y-m-d H:i:s')
	{
		if ($this->finished1 === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->finished1);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->finished1, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [started2] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getStarted2($format = 'Y-m-d H:i:s')
	{
		if ($this->started2 === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->started2);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->started2, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [finished2] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFinished2($format = 'Y-m-d H:i:s')
	{
		if ($this->finished2 === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->finished2);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->finished2, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [finished] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFinished($format = 'Y-m-d H:i:s')
	{
		if ($this->finished === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->finished);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->finished, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     string
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [collection_name] column value.
	 * 
	 * @return     string
	 */
	public function getCollectionName()
	{
		return $this->collection_name;
	}

	/**
	 * Get the [log] column value.
	 * 
	 * @return     string
	 */
	public function getLog()
	{
		return $this->log;
	}

	/**
	 * Get the [external_key] column value.
	 * 
	 * @return     string
	 */
	public function getExternalKey()
	{
		return $this->external_key;
	}

	/**
	 * Get the [guid] column value.
	 * 
	 * @return     string
	 */
	public function getGuid()
	{
		return $this->guid;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = SmafejobAddfilePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [priority] column.
	 * 
	 * @param      int $v new value
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setPriority($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->priority !== $v || $this->isNew()) {
			$this->priority = $v;
			$this->modifiedColumns[] = SmafejobAddfilePeer::PRIORITY;
		}

		return $this;
	} // setPriority()

	/**
	 * Set the value of [file_uri] column.
	 * 
	 * @param      string $v new value
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setFileUri($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->file_uri !== $v) {
			$this->file_uri = $v;
			$this->modifiedColumns[] = SmafejobAddfilePeer::FILE_URI;
		}

		return $this;
	} // setFileUri()

	/**
	 * Sets the value of [created] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setCreated($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created !== null && $tmpDt = new DateTime($this->created)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					|| ($dt->format('Y-m-d\\TH:i:sO') === '-99999--99999--99999T-99999:-99999:-99999+0000') // or the entered value matches the default
					)
			{
				$this->created = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = SmafejobAddfilePeer::CREATED;
			}
		} // if either are not null

		return $this;
	} // setCreated()

	/**
	 * Sets the value of [started] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setStarted($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->started !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->started !== null && $tmpDt = new DateTime($this->started)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->started = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = SmafejobAddfilePeer::STARTED;
			}
		} // if either are not null

		return $this;
	} // setStarted()

	/**
	 * Sets the value of [finished1] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setFinished1($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->finished1 !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->finished1 !== null && $tmpDt = new DateTime($this->finished1)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->finished1 = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = SmafejobAddfilePeer::FINISHED1;
			}
		} // if either are not null

		return $this;
	} // setFinished1()

	/**
	 * Sets the value of [started2] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setStarted2($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->started2 !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->started2 !== null && $tmpDt = new DateTime($this->started2)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->started2 = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = SmafejobAddfilePeer::STARTED2;
			}
		} // if either are not null

		return $this;
	} // setStarted2()

	/**
	 * Sets the value of [finished2] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setFinished2($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->finished2 !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->finished2 !== null && $tmpDt = new DateTime($this->finished2)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->finished2 = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = SmafejobAddfilePeer::FINISHED2;
			}
		} // if either are not null

		return $this;
	} // setFinished2()

	/**
	 * Sets the value of [finished] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setFinished($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->finished !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->finished !== null && $tmpDt = new DateTime($this->finished)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->finished = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = SmafejobAddfilePeer::FINISHED;
			}
		} // if either are not null

		return $this;
	} // setFinished()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      string $v new value
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->status !== $v) {
			$this->status = $v;
			$this->modifiedColumns[] = SmafejobAddfilePeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Set the value of [collection_name] column.
	 * 
	 * @param      string $v new value
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setCollectionName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->collection_name !== $v) {
			$this->collection_name = $v;
			$this->modifiedColumns[] = SmafejobAddfilePeer::COLLECTION_NAME;
		}

		return $this;
	} // setCollectionName()

	/**
	 * Set the value of [log] column.
	 * 
	 * @param      string $v new value
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setLog($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->log !== $v) {
			$this->log = $v;
			$this->modifiedColumns[] = SmafejobAddfilePeer::LOG;
		}

		return $this;
	} // setLog()

	/**
	 * Set the value of [external_key] column.
	 * 
	 * @param      string $v new value
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setExternalKey($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->external_key !== $v) {
			$this->external_key = $v;
			$this->modifiedColumns[] = SmafejobAddfilePeer::EXTERNAL_KEY;
		}

		return $this;
	} // setExternalKey()

	/**
	 * Set the value of [guid] column.
	 * 
	 * @param      string $v new value
	 * @return     SmafejobAddfile The current object (for fluent API support)
	 */
	public function setGuid($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->guid !== $v) {
			$this->guid = $v;
			$this->modifiedColumns[] = SmafejobAddfilePeer::GUID;
		}

		return $this;
	} // setGuid()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->priority !== 0) {
				return false;
			}

			if ($this->created !== '-99999--99999--99999T-99999:-99999:-99999+0000') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->priority = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->file_uri = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->created = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->started = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->finished1 = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->started2 = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->finished2 = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->finished = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->status = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->collection_name = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->log = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->external_key = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->guid = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 14; // 14 = SmafejobAddfilePeer::NUM_COLUMNS - SmafejobAddfilePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating SmafejobAddfile object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SmafejobAddfilePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = SmafejobAddfilePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collDistancejobs = null;
			$this->lastDistancejobCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SmafejobAddfilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSmafejobAddfile:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				SmafejobAddfilePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSmafejobAddfile:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SmafejobAddfilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSmafejobAddfile:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSmafejobAddfile:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				SmafejobAddfilePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = SmafejobAddfilePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = SmafejobAddfilePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += SmafejobAddfilePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collDistancejobs !== null) {
				foreach ($this->collDistancejobs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = SmafejobAddfilePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collDistancejobs !== null) {
					foreach ($this->collDistancejobs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SmafejobAddfilePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPriority();
				break;
			case 2:
				return $this->getFileUri();
				break;
			case 3:
				return $this->getCreated();
				break;
			case 4:
				return $this->getStarted();
				break;
			case 5:
				return $this->getFinished1();
				break;
			case 6:
				return $this->getStarted2();
				break;
			case 7:
				return $this->getFinished2();
				break;
			case 8:
				return $this->getFinished();
				break;
			case 9:
				return $this->getStatus();
				break;
			case 10:
				return $this->getCollectionName();
				break;
			case 11:
				return $this->getLog();
				break;
			case 12:
				return $this->getExternalKey();
				break;
			case 13:
				return $this->getGuid();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = SmafejobAddfilePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPriority(),
			$keys[2] => $this->getFileUri(),
			$keys[3] => $this->getCreated(),
			$keys[4] => $this->getStarted(),
			$keys[5] => $this->getFinished1(),
			$keys[6] => $this->getStarted2(),
			$keys[7] => $this->getFinished2(),
			$keys[8] => $this->getFinished(),
			$keys[9] => $this->getStatus(),
			$keys[10] => $this->getCollectionName(),
			$keys[11] => $this->getLog(),
			$keys[12] => $this->getExternalKey(),
			$keys[13] => $this->getGuid(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SmafejobAddfilePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPriority($value);
				break;
			case 2:
				$this->setFileUri($value);
				break;
			case 3:
				$this->setCreated($value);
				break;
			case 4:
				$this->setStarted($value);
				break;
			case 5:
				$this->setFinished1($value);
				break;
			case 6:
				$this->setStarted2($value);
				break;
			case 7:
				$this->setFinished2($value);
				break;
			case 8:
				$this->setFinished($value);
				break;
			case 9:
				$this->setStatus($value);
				break;
			case 10:
				$this->setCollectionName($value);
				break;
			case 11:
				$this->setLog($value);
				break;
			case 12:
				$this->setExternalKey($value);
				break;
			case 13:
				$this->setGuid($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = SmafejobAddfilePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPriority($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFileUri($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCreated($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setStarted($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFinished1($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setStarted2($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setFinished2($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFinished($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setStatus($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setCollectionName($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setLog($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setExternalKey($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setGuid($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(SmafejobAddfilePeer::DATABASE_NAME);

		if ($this->isColumnModified(SmafejobAddfilePeer::ID)) $criteria->add(SmafejobAddfilePeer::ID, $this->id);
		if ($this->isColumnModified(SmafejobAddfilePeer::PRIORITY)) $criteria->add(SmafejobAddfilePeer::PRIORITY, $this->priority);
		if ($this->isColumnModified(SmafejobAddfilePeer::FILE_URI)) $criteria->add(SmafejobAddfilePeer::FILE_URI, $this->file_uri);
		if ($this->isColumnModified(SmafejobAddfilePeer::CREATED)) $criteria->add(SmafejobAddfilePeer::CREATED, $this->created);
		if ($this->isColumnModified(SmafejobAddfilePeer::STARTED)) $criteria->add(SmafejobAddfilePeer::STARTED, $this->started);
		if ($this->isColumnModified(SmafejobAddfilePeer::FINISHED1)) $criteria->add(SmafejobAddfilePeer::FINISHED1, $this->finished1);
		if ($this->isColumnModified(SmafejobAddfilePeer::STARTED2)) $criteria->add(SmafejobAddfilePeer::STARTED2, $this->started2);
		if ($this->isColumnModified(SmafejobAddfilePeer::FINISHED2)) $criteria->add(SmafejobAddfilePeer::FINISHED2, $this->finished2);
		if ($this->isColumnModified(SmafejobAddfilePeer::FINISHED)) $criteria->add(SmafejobAddfilePeer::FINISHED, $this->finished);
		if ($this->isColumnModified(SmafejobAddfilePeer::STATUS)) $criteria->add(SmafejobAddfilePeer::STATUS, $this->status);
		if ($this->isColumnModified(SmafejobAddfilePeer::COLLECTION_NAME)) $criteria->add(SmafejobAddfilePeer::COLLECTION_NAME, $this->collection_name);
		if ($this->isColumnModified(SmafejobAddfilePeer::LOG)) $criteria->add(SmafejobAddfilePeer::LOG, $this->log);
		if ($this->isColumnModified(SmafejobAddfilePeer::EXTERNAL_KEY)) $criteria->add(SmafejobAddfilePeer::EXTERNAL_KEY, $this->external_key);
		if ($this->isColumnModified(SmafejobAddfilePeer::GUID)) $criteria->add(SmafejobAddfilePeer::GUID, $this->guid);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(SmafejobAddfilePeer::DATABASE_NAME);

		$criteria->add(SmafejobAddfilePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of SmafejobAddfile (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPriority($this->priority);

		$copyObj->setFileUri($this->file_uri);

		$copyObj->setCreated($this->created);

		$copyObj->setStarted($this->started);

		$copyObj->setFinished1($this->finished1);

		$copyObj->setStarted2($this->started2);

		$copyObj->setFinished2($this->finished2);

		$copyObj->setFinished($this->finished);

		$copyObj->setStatus($this->status);

		$copyObj->setCollectionName($this->collection_name);

		$copyObj->setLog($this->log);

		$copyObj->setExternalKey($this->external_key);

		$copyObj->setGuid($this->guid);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getDistancejobs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addDistancejob($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     SmafejobAddfile Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     SmafejobAddfilePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new SmafejobAddfilePeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collDistancejobs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addDistancejobs()
	 */
	public function clearDistancejobs()
	{
		$this->collDistancejobs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collDistancejobs collection (array).
	 *
	 * By default this just sets the collDistancejobs collection to an empty array (like clearcollDistancejobs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initDistancejobs()
	{
		$this->collDistancejobs = array();
	}

	/**
	 * Gets an array of Distancejob objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SmafejobAddfile has previously been saved, it will retrieve
	 * related Distancejobs from storage. If this SmafejobAddfile is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Distancejob[]
	 * @throws     PropelException
	 */
	public function getDistancejobs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SmafejobAddfilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDistancejobs === null) {
			if ($this->isNew()) {
			   $this->collDistancejobs = array();
			} else {

				$criteria->add(DistancejobPeer::SMAFEJOB_ADDFILE_ID, $this->id);

				DistancejobPeer::addSelectColumns($criteria);
				$this->collDistancejobs = DistancejobPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(DistancejobPeer::SMAFEJOB_ADDFILE_ID, $this->id);

				DistancejobPeer::addSelectColumns($criteria);
				if (!isset($this->lastDistancejobCriteria) || !$this->lastDistancejobCriteria->equals($criteria)) {
					$this->collDistancejobs = DistancejobPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastDistancejobCriteria = $criteria;
		return $this->collDistancejobs;
	}

	/**
	 * Returns the number of related Distancejob objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Distancejob objects.
	 * @throws     PropelException
	 */
	public function countDistancejobs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SmafejobAddfilePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collDistancejobs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(DistancejobPeer::SMAFEJOB_ADDFILE_ID, $this->id);

				$count = DistancejobPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(DistancejobPeer::SMAFEJOB_ADDFILE_ID, $this->id);

				if (!isset($this->lastDistancejobCriteria) || !$this->lastDistancejobCriteria->equals($criteria)) {
					$count = DistancejobPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collDistancejobs);
				}
			} else {
				$count = count($this->collDistancejobs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Distancejob object to this object
	 * through the Distancejob foreign key attribute.
	 *
	 * @param      Distancejob $l Distancejob
	 * @return     void
	 * @throws     PropelException
	 */
	public function addDistancejob(Distancejob $l)
	{
		if ($this->collDistancejobs === null) {
			$this->initDistancejobs();
		}
		if (!in_array($l, $this->collDistancejobs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collDistancejobs, $l);
			$l->setSmafejobAddfile($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SmafejobAddfile is new, it will return
	 * an empty collection; or if this SmafejobAddfile has previously
	 * been saved, it will retrieve related Distancejobs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SmafejobAddfile.
	 */
	public function getDistancejobsJoinFeaturevector($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SmafejobAddfilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDistancejobs === null) {
			if ($this->isNew()) {
				$this->collDistancejobs = array();
			} else {

				$criteria->add(DistancejobPeer::SMAFEJOB_ADDFILE_ID, $this->id);

				$this->collDistancejobs = DistancejobPeer::doSelectJoinFeaturevector($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DistancejobPeer::SMAFEJOB_ADDFILE_ID, $this->id);

			if (!isset($this->lastDistancejobCriteria) || !$this->lastDistancejobCriteria->equals($criteria)) {
				$this->collDistancejobs = DistancejobPeer::doSelectJoinFeaturevector($criteria, $con, $join_behavior);
			}
		}
		$this->lastDistancejobCriteria = $criteria;

		return $this->collDistancejobs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SmafejobAddfile is new, it will return
	 * an empty collection; or if this SmafejobAddfile has previously
	 * been saved, it will retrieve related Distancejobs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SmafejobAddfile.
	 */
	public function getDistancejobsJoinDistancetype($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SmafejobAddfilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDistancejobs === null) {
			if ($this->isNew()) {
				$this->collDistancejobs = array();
			} else {

				$criteria->add(DistancejobPeer::SMAFEJOB_ADDFILE_ID, $this->id);

				$this->collDistancejobs = DistancejobPeer::doSelectJoinDistancetype($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DistancejobPeer::SMAFEJOB_ADDFILE_ID, $this->id);

			if (!isset($this->lastDistancejobCriteria) || !$this->lastDistancejobCriteria->equals($criteria)) {
				$this->collDistancejobs = DistancejobPeer::doSelectJoinDistancetype($criteria, $con, $join_behavior);
			}
		}
		$this->lastDistancejobCriteria = $criteria;

		return $this->collDistancejobs;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collDistancejobs) {
				foreach ((array) $this->collDistancejobs as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collDistancejobs = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseSmafejobAddfile:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseSmafejobAddfile::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseSmafejobAddfile
