<?php

/**
 * Base class that represents a row from the 'featurevectortype' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 30 15:27:45 2012
 *
 * @package    lib.model.smafe.om
 */
abstract class BaseFeaturevectortype extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FeaturevectortypePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the version field.
	 * @var        int
	 */
	protected $version;

	/**
	 * The value for the dimension_x field.
	 * @var        int
	 */
	protected $dimension_x;

	/**
	 * The value for the dimension_y field.
	 * @var        int
	 */
	protected $dimension_y;

	/**
	 * The value for the parameters field.
	 * @var        string
	 */
	protected $parameters;

	/**
	 * The value for the class_id field.
	 * @var        string
	 */
	protected $class_id;

	/**
	 * The value for the inserted field.
	 * @var        string
	 */
	protected $inserted;

	/**
	 * The value for the updated field.
	 * @var        string
	 */
	protected $updated;

	/**
	 * @var        array Featurevector[] Collection to store aggregation of Featurevector objects.
	 */
	protected $collFeaturevectors;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFeaturevectors.
	 */
	private $lastFeaturevectorCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'FeaturevectortypePeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [version] column value.
	 * 
	 * @return     int
	 */
	public function getVersion()
	{
		return $this->version;
	}

	/**
	 * Get the [dimension_x] column value.
	 * 
	 * @return     int
	 */
	public function getDimensionX()
	{
		return $this->dimension_x;
	}

	/**
	 * Get the [dimension_y] column value.
	 * 
	 * @return     int
	 */
	public function getDimensionY()
	{
		return $this->dimension_y;
	}

	/**
	 * Get the [parameters] column value.
	 * 
	 * @return     string
	 */
	public function getParameters()
	{
		return $this->parameters;
	}

	/**
	 * Get the [class_id] column value.
	 * 
	 * @return     string
	 */
	public function getClassId()
	{
		return $this->class_id;
	}

	/**
	 * Get the [optionally formatted] temporal [inserted] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getInserted($format = 'Y-m-d H:i:s')
	{
		if ($this->inserted === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->inserted);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->inserted, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdated($format = 'Y-m-d H:i:s')
	{
		if ($this->updated === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Featurevectortype The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = FeaturevectortypePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Featurevectortype The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = FeaturevectortypePeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [version] column.
	 * 
	 * @param      int $v new value
	 * @return     Featurevectortype The current object (for fluent API support)
	 */
	public function setVersion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->version !== $v) {
			$this->version = $v;
			$this->modifiedColumns[] = FeaturevectortypePeer::VERSION;
		}

		return $this;
	} // setVersion()

	/**
	 * Set the value of [dimension_x] column.
	 * 
	 * @param      int $v new value
	 * @return     Featurevectortype The current object (for fluent API support)
	 */
	public function setDimensionX($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->dimension_x !== $v) {
			$this->dimension_x = $v;
			$this->modifiedColumns[] = FeaturevectortypePeer::DIMENSION_X;
		}

		return $this;
	} // setDimensionX()

	/**
	 * Set the value of [dimension_y] column.
	 * 
	 * @param      int $v new value
	 * @return     Featurevectortype The current object (for fluent API support)
	 */
	public function setDimensionY($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->dimension_y !== $v) {
			$this->dimension_y = $v;
			$this->modifiedColumns[] = FeaturevectortypePeer::DIMENSION_Y;
		}

		return $this;
	} // setDimensionY()

	/**
	 * Set the value of [parameters] column.
	 * 
	 * @param      string $v new value
	 * @return     Featurevectortype The current object (for fluent API support)
	 */
	public function setParameters($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->parameters !== $v) {
			$this->parameters = $v;
			$this->modifiedColumns[] = FeaturevectortypePeer::PARAMETERS;
		}

		return $this;
	} // setParameters()

	/**
	 * Set the value of [class_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Featurevectortype The current object (for fluent API support)
	 */
	public function setClassId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->class_id !== $v) {
			$this->class_id = $v;
			$this->modifiedColumns[] = FeaturevectortypePeer::CLASS_ID;
		}

		return $this;
	} // setClassId()

	/**
	 * Sets the value of [inserted] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Featurevectortype The current object (for fluent API support)
	 */
	public function setInserted($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->inserted !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->inserted !== null && $tmpDt = new DateTime($this->inserted)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->inserted = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = FeaturevectortypePeer::INSERTED;
			}
		} // if either are not null

		return $this;
	} // setInserted()

	/**
	 * Sets the value of [updated] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Featurevectortype The current object (for fluent API support)
	 */
	public function setUpdated($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated !== null && $tmpDt = new DateTime($this->updated)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = FeaturevectortypePeer::UPDATED;
			}
		} // if either are not null

		return $this;
	} // setUpdated()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->version = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->dimension_x = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->dimension_y = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->parameters = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->class_id = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->inserted = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->updated = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = FeaturevectortypePeer::NUM_COLUMNS - FeaturevectortypePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Featurevectortype object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FeaturevectortypePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FeaturevectortypePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collFeaturevectors = null;
			$this->lastFeaturevectorCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FeaturevectortypePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFeaturevectortype:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				FeaturevectortypePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFeaturevectortype:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FeaturevectortypePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFeaturevectortype:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFeaturevectortype:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				FeaturevectortypePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FeaturevectortypePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FeaturevectortypePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FeaturevectortypePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collFeaturevectors !== null) {
				foreach ($this->collFeaturevectors as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = FeaturevectortypePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collFeaturevectors !== null) {
					foreach ($this->collFeaturevectors as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FeaturevectortypePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getVersion();
				break;
			case 3:
				return $this->getDimensionX();
				break;
			case 4:
				return $this->getDimensionY();
				break;
			case 5:
				return $this->getParameters();
				break;
			case 6:
				return $this->getClassId();
				break;
			case 7:
				return $this->getInserted();
				break;
			case 8:
				return $this->getUpdated();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FeaturevectortypePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getVersion(),
			$keys[3] => $this->getDimensionX(),
			$keys[4] => $this->getDimensionY(),
			$keys[5] => $this->getParameters(),
			$keys[6] => $this->getClassId(),
			$keys[7] => $this->getInserted(),
			$keys[8] => $this->getUpdated(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FeaturevectortypePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setVersion($value);
				break;
			case 3:
				$this->setDimensionX($value);
				break;
			case 4:
				$this->setDimensionY($value);
				break;
			case 5:
				$this->setParameters($value);
				break;
			case 6:
				$this->setClassId($value);
				break;
			case 7:
				$this->setInserted($value);
				break;
			case 8:
				$this->setUpdated($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FeaturevectortypePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setVersion($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDimensionX($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDimensionY($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setParameters($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setClassId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setInserted($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUpdated($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FeaturevectortypePeer::DATABASE_NAME);

		if ($this->isColumnModified(FeaturevectortypePeer::ID)) $criteria->add(FeaturevectortypePeer::ID, $this->id);
		if ($this->isColumnModified(FeaturevectortypePeer::NAME)) $criteria->add(FeaturevectortypePeer::NAME, $this->name);
		if ($this->isColumnModified(FeaturevectortypePeer::VERSION)) $criteria->add(FeaturevectortypePeer::VERSION, $this->version);
		if ($this->isColumnModified(FeaturevectortypePeer::DIMENSION_X)) $criteria->add(FeaturevectortypePeer::DIMENSION_X, $this->dimension_x);
		if ($this->isColumnModified(FeaturevectortypePeer::DIMENSION_Y)) $criteria->add(FeaturevectortypePeer::DIMENSION_Y, $this->dimension_y);
		if ($this->isColumnModified(FeaturevectortypePeer::PARAMETERS)) $criteria->add(FeaturevectortypePeer::PARAMETERS, $this->parameters);
		if ($this->isColumnModified(FeaturevectortypePeer::CLASS_ID)) $criteria->add(FeaturevectortypePeer::CLASS_ID, $this->class_id);
		if ($this->isColumnModified(FeaturevectortypePeer::INSERTED)) $criteria->add(FeaturevectortypePeer::INSERTED, $this->inserted);
		if ($this->isColumnModified(FeaturevectortypePeer::UPDATED)) $criteria->add(FeaturevectortypePeer::UPDATED, $this->updated);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FeaturevectortypePeer::DATABASE_NAME);

		$criteria->add(FeaturevectortypePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Featurevectortype (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setVersion($this->version);

		$copyObj->setDimensionX($this->dimension_x);

		$copyObj->setDimensionY($this->dimension_y);

		$copyObj->setParameters($this->parameters);

		$copyObj->setClassId($this->class_id);

		$copyObj->setInserted($this->inserted);

		$copyObj->setUpdated($this->updated);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getFeaturevectors() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFeaturevector($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Featurevectortype Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FeaturevectortypePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FeaturevectortypePeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collFeaturevectors collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFeaturevectors()
	 */
	public function clearFeaturevectors()
	{
		$this->collFeaturevectors = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFeaturevectors collection (array).
	 *
	 * By default this just sets the collFeaturevectors collection to an empty array (like clearcollFeaturevectors());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFeaturevectors()
	{
		$this->collFeaturevectors = array();
	}

	/**
	 * Gets an array of Featurevector objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Featurevectortype has previously been saved, it will retrieve
	 * related Featurevectors from storage. If this Featurevectortype is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Featurevector[]
	 * @throws     PropelException
	 */
	public function getFeaturevectors($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FeaturevectortypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFeaturevectors === null) {
			if ($this->isNew()) {
			   $this->collFeaturevectors = array();
			} else {

				$criteria->add(FeaturevectorPeer::FEATUREVECTORTYPE_ID, $this->id);

				FeaturevectorPeer::addSelectColumns($criteria);
				$this->collFeaturevectors = FeaturevectorPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FeaturevectorPeer::FEATUREVECTORTYPE_ID, $this->id);

				FeaturevectorPeer::addSelectColumns($criteria);
				if (!isset($this->lastFeaturevectorCriteria) || !$this->lastFeaturevectorCriteria->equals($criteria)) {
					$this->collFeaturevectors = FeaturevectorPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFeaturevectorCriteria = $criteria;
		return $this->collFeaturevectors;
	}

	/**
	 * Returns the number of related Featurevector objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Featurevector objects.
	 * @throws     PropelException
	 */
	public function countFeaturevectors(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FeaturevectortypePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFeaturevectors === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FeaturevectorPeer::FEATUREVECTORTYPE_ID, $this->id);

				$count = FeaturevectorPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FeaturevectorPeer::FEATUREVECTORTYPE_ID, $this->id);

				if (!isset($this->lastFeaturevectorCriteria) || !$this->lastFeaturevectorCriteria->equals($criteria)) {
					$count = FeaturevectorPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collFeaturevectors);
				}
			} else {
				$count = count($this->collFeaturevectors);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Featurevector object to this object
	 * through the Featurevector foreign key attribute.
	 *
	 * @param      Featurevector $l Featurevector
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFeaturevector(Featurevector $l)
	{
		if ($this->collFeaturevectors === null) {
			$this->initFeaturevectors();
		}
		if (!in_array($l, $this->collFeaturevectors, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFeaturevectors, $l);
			$l->setFeaturevectortype($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Featurevectortype is new, it will return
	 * an empty collection; or if this Featurevectortype has previously
	 * been saved, it will retrieve related Featurevectors from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Featurevectortype.
	 */
	public function getFeaturevectorsJoinTrack($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FeaturevectortypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFeaturevectors === null) {
			if ($this->isNew()) {
				$this->collFeaturevectors = array();
			} else {

				$criteria->add(FeaturevectorPeer::FEATUREVECTORTYPE_ID, $this->id);

				$this->collFeaturevectors = FeaturevectorPeer::doSelectJoinTrack($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FeaturevectorPeer::FEATUREVECTORTYPE_ID, $this->id);

			if (!isset($this->lastFeaturevectorCriteria) || !$this->lastFeaturevectorCriteria->equals($criteria)) {
				$this->collFeaturevectors = FeaturevectorPeer::doSelectJoinTrack($criteria, $con, $join_behavior);
			}
		}
		$this->lastFeaturevectorCriteria = $criteria;

		return $this->collFeaturevectors;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Featurevectortype is new, it will return
	 * an empty collection; or if this Featurevectortype has previously
	 * been saved, it will retrieve related Featurevectors from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Featurevectortype.
	 */
	public function getFeaturevectorsJoinFile($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FeaturevectortypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFeaturevectors === null) {
			if ($this->isNew()) {
				$this->collFeaturevectors = array();
			} else {

				$criteria->add(FeaturevectorPeer::FEATUREVECTORTYPE_ID, $this->id);

				$this->collFeaturevectors = FeaturevectorPeer::doSelectJoinFile($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FeaturevectorPeer::FEATUREVECTORTYPE_ID, $this->id);

			if (!isset($this->lastFeaturevectorCriteria) || !$this->lastFeaturevectorCriteria->equals($criteria)) {
				$this->collFeaturevectors = FeaturevectorPeer::doSelectJoinFile($criteria, $con, $join_behavior);
			}
		}
		$this->lastFeaturevectorCriteria = $criteria;

		return $this->collFeaturevectors;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collFeaturevectors) {
				foreach ((array) $this->collFeaturevectors as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collFeaturevectors = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseFeaturevectortype:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseFeaturevectortype::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseFeaturevectortype
