<?php

/**
 * Base class that represents a row from the 'file' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 30 15:27:45 2012
 *
 * @package    lib.model.smafe.om
 */
abstract class BaseFile extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FilePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the hash field.
	 * @var        string
	 */
	protected $hash;

	/**
	 * The value for the track_id field.
	 * @var        int
	 */
	protected $track_id;

	/**
	 * The value for the inserted field.
	 * Note: this column has a database default value of: '-99999--99999--99999T-99999:-99999:-99999+0000'
	 * @var        string
	 */
	protected $inserted;

	/**
	 * The value for the updated field.
	 * @var        string
	 */
	protected $updated;

	/**
	 * The value for the input_format field.
	 * @var        string
	 */
	protected $input_format;

	/**
	 * The value for the uri field.
	 * @var        string
	 */
	protected $uri;

	/**
	 * The value for the samplef field.
	 * @var        int
	 */
	protected $samplef;

	/**
	 * The value for the bitrate field.
	 * @var        int
	 */
	protected $bitrate;

	/**
	 * The value for the channels field.
	 * @var        int
	 */
	protected $channels;

	/**
	 * The value for the encoding field.
	 * @var        string
	 */
	protected $encoding;

	/**
	 * The value for the samplebit field.
	 * @var        int
	 */
	protected $samplebit;

	/**
	 * The value for the external_key field.
	 * @var        string
	 */
	protected $external_key;

	/**
	 * The value for the guid field.
	 * @var        string
	 */
	protected $guid;

	/**
	 * @var        Track
	 */
	protected $aTrack;

	/**
	 * @var        array CollectionFile[] Collection to store aggregation of CollectionFile objects.
	 */
	protected $collCollectionFiles;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCollectionFiles.
	 */
	private $lastCollectionFileCriteria = null;

	/**
	 * @var        array Featurevector[] Collection to store aggregation of Featurevector objects.
	 */
	protected $collFeaturevectors;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFeaturevectors.
	 */
	private $lastFeaturevectorCriteria = null;

	/**
	 * @var        array Featurevectorsegment[] Collection to store aggregation of Featurevectorsegment objects.
	 */
	protected $collFeaturevectorsegments;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFeaturevectorsegments.
	 */
	private $lastFeaturevectorsegmentCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'FilePeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->inserted = '-99999--99999--99999T-99999:-99999:-99999+0000';
	}

	/**
	 * Initializes internal state of BaseFile object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [hash] column value.
	 * 
	 * @return     string
	 */
	public function getHash()
	{
		return $this->hash;
	}

	/**
	 * Get the [track_id] column value.
	 * 
	 * @return     int
	 */
	public function getTrackId()
	{
		return $this->track_id;
	}

	/**
	 * Get the [optionally formatted] temporal [inserted] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getInserted($format = 'Y-m-d H:i:s')
	{
		if ($this->inserted === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->inserted);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->inserted, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdated($format = 'Y-m-d H:i:s')
	{
		if ($this->updated === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [input_format] column value.
	 * 
	 * @return     string
	 */
	public function getInputFormat()
	{
		return $this->input_format;
	}

	/**
	 * Get the [uri] column value.
	 * 
	 * @return     string
	 */
	public function getUri()
	{
		return $this->uri;
	}

	/**
	 * Get the [samplef] column value.
	 * 
	 * @return     int
	 */
	public function getSamplef()
	{
		return $this->samplef;
	}

	/**
	 * Get the [bitrate] column value.
	 * 
	 * @return     int
	 */
	public function getBitrate()
	{
		return $this->bitrate;
	}

	/**
	 * Get the [channels] column value.
	 * 
	 * @return     int
	 */
	public function getChannels()
	{
		return $this->channels;
	}

	/**
	 * Get the [encoding] column value.
	 * 
	 * @return     string
	 */
	public function getEncoding()
	{
		return $this->encoding;
	}

	/**
	 * Get the [samplebit] column value.
	 * 
	 * @return     int
	 */
	public function getSamplebit()
	{
		return $this->samplebit;
	}

	/**
	 * Get the [external_key] column value.
	 * 
	 * @return     string
	 */
	public function getExternalKey()
	{
		return $this->external_key;
	}

	/**
	 * Get the [guid] column value.
	 * 
	 * @return     string
	 */
	public function getGuid()
	{
		return $this->guid;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = FilePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [hash] column.
	 * 
	 * @param      string $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setHash($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->hash !== $v) {
			$this->hash = $v;
			$this->modifiedColumns[] = FilePeer::HASH;
		}

		return $this;
	} // setHash()

	/**
	 * Set the value of [track_id] column.
	 * 
	 * @param      int $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setTrackId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->track_id !== $v) {
			$this->track_id = $v;
			$this->modifiedColumns[] = FilePeer::TRACK_ID;
		}

		if ($this->aTrack !== null && $this->aTrack->getId() !== $v) {
			$this->aTrack = null;
		}

		return $this;
	} // setTrackId()

	/**
	 * Sets the value of [inserted] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     File The current object (for fluent API support)
	 */
	public function setInserted($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->inserted !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->inserted !== null && $tmpDt = new DateTime($this->inserted)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					|| ($dt->format('Y-m-d\\TH:i:sO') === '-99999--99999--99999T-99999:-99999:-99999+0000') // or the entered value matches the default
					)
			{
				$this->inserted = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = FilePeer::INSERTED;
			}
		} // if either are not null

		return $this;
	} // setInserted()

	/**
	 * Sets the value of [updated] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     File The current object (for fluent API support)
	 */
	public function setUpdated($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated !== null && $tmpDt = new DateTime($this->updated)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = FilePeer::UPDATED;
			}
		} // if either are not null

		return $this;
	} // setUpdated()

	/**
	 * Set the value of [input_format] column.
	 * 
	 * @param      string $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setInputFormat($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->input_format !== $v) {
			$this->input_format = $v;
			$this->modifiedColumns[] = FilePeer::INPUT_FORMAT;
		}

		return $this;
	} // setInputFormat()

	/**
	 * Set the value of [uri] column.
	 * 
	 * @param      string $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setUri($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->uri !== $v) {
			$this->uri = $v;
			$this->modifiedColumns[] = FilePeer::URI;
		}

		return $this;
	} // setUri()

	/**
	 * Set the value of [samplef] column.
	 * 
	 * @param      int $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setSamplef($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->samplef !== $v) {
			$this->samplef = $v;
			$this->modifiedColumns[] = FilePeer::SAMPLEF;
		}

		return $this;
	} // setSamplef()

	/**
	 * Set the value of [bitrate] column.
	 * 
	 * @param      int $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setBitrate($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->bitrate !== $v) {
			$this->bitrate = $v;
			$this->modifiedColumns[] = FilePeer::BITRATE;
		}

		return $this;
	} // setBitrate()

	/**
	 * Set the value of [channels] column.
	 * 
	 * @param      int $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setChannels($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->channels !== $v) {
			$this->channels = $v;
			$this->modifiedColumns[] = FilePeer::CHANNELS;
		}

		return $this;
	} // setChannels()

	/**
	 * Set the value of [encoding] column.
	 * 
	 * @param      string $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setEncoding($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->encoding !== $v) {
			$this->encoding = $v;
			$this->modifiedColumns[] = FilePeer::ENCODING;
		}

		return $this;
	} // setEncoding()

	/**
	 * Set the value of [samplebit] column.
	 * 
	 * @param      int $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setSamplebit($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->samplebit !== $v) {
			$this->samplebit = $v;
			$this->modifiedColumns[] = FilePeer::SAMPLEBIT;
		}

		return $this;
	} // setSamplebit()

	/**
	 * Set the value of [external_key] column.
	 * 
	 * @param      string $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setExternalKey($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->external_key !== $v) {
			$this->external_key = $v;
			$this->modifiedColumns[] = FilePeer::EXTERNAL_KEY;
		}

		return $this;
	} // setExternalKey()

	/**
	 * Set the value of [guid] column.
	 * 
	 * @param      string $v new value
	 * @return     File The current object (for fluent API support)
	 */
	public function setGuid($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->guid !== $v) {
			$this->guid = $v;
			$this->modifiedColumns[] = FilePeer::GUID;
		}

		return $this;
	} // setGuid()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->inserted !== '-99999--99999--99999T-99999:-99999:-99999+0000') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->hash = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->track_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->inserted = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->updated = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->input_format = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->uri = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->samplef = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->bitrate = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->channels = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->encoding = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->samplebit = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->external_key = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->guid = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 14; // 14 = FilePeer::NUM_COLUMNS - FilePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating File object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTrack !== null && $this->track_id !== $this->aTrack->getId()) {
			$this->aTrack = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FilePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FilePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTrack = null;
			$this->collCollectionFiles = null;
			$this->lastCollectionFileCriteria = null;

			$this->collFeaturevectors = null;
			$this->lastFeaturevectorCriteria = null;

			$this->collFeaturevectorsegments = null;
			$this->lastFeaturevectorsegmentCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFile:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				FilePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFile:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFile:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFile:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				FilePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTrack !== null) {
				if ($this->aTrack->isModified() || $this->aTrack->isNew()) {
					$affectedRows += $this->aTrack->save($con);
				}
				$this->setTrack($this->aTrack);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FilePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FilePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FilePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCollectionFiles !== null) {
				foreach ($this->collCollectionFiles as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collFeaturevectors !== null) {
				foreach ($this->collFeaturevectors as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collFeaturevectorsegments !== null) {
				foreach ($this->collFeaturevectorsegments as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTrack !== null) {
				if (!$this->aTrack->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTrack->getValidationFailures());
				}
			}


			if (($retval = FilePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCollectionFiles !== null) {
					foreach ($this->collCollectionFiles as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collFeaturevectors !== null) {
					foreach ($this->collFeaturevectors as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collFeaturevectorsegments !== null) {
					foreach ($this->collFeaturevectorsegments as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FilePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getHash();
				break;
			case 2:
				return $this->getTrackId();
				break;
			case 3:
				return $this->getInserted();
				break;
			case 4:
				return $this->getUpdated();
				break;
			case 5:
				return $this->getInputFormat();
				break;
			case 6:
				return $this->getUri();
				break;
			case 7:
				return $this->getSamplef();
				break;
			case 8:
				return $this->getBitrate();
				break;
			case 9:
				return $this->getChannels();
				break;
			case 10:
				return $this->getEncoding();
				break;
			case 11:
				return $this->getSamplebit();
				break;
			case 12:
				return $this->getExternalKey();
				break;
			case 13:
				return $this->getGuid();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FilePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getHash(),
			$keys[2] => $this->getTrackId(),
			$keys[3] => $this->getInserted(),
			$keys[4] => $this->getUpdated(),
			$keys[5] => $this->getInputFormat(),
			$keys[6] => $this->getUri(),
			$keys[7] => $this->getSamplef(),
			$keys[8] => $this->getBitrate(),
			$keys[9] => $this->getChannels(),
			$keys[10] => $this->getEncoding(),
			$keys[11] => $this->getSamplebit(),
			$keys[12] => $this->getExternalKey(),
			$keys[13] => $this->getGuid(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FilePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setHash($value);
				break;
			case 2:
				$this->setTrackId($value);
				break;
			case 3:
				$this->setInserted($value);
				break;
			case 4:
				$this->setUpdated($value);
				break;
			case 5:
				$this->setInputFormat($value);
				break;
			case 6:
				$this->setUri($value);
				break;
			case 7:
				$this->setSamplef($value);
				break;
			case 8:
				$this->setBitrate($value);
				break;
			case 9:
				$this->setChannels($value);
				break;
			case 10:
				$this->setEncoding($value);
				break;
			case 11:
				$this->setSamplebit($value);
				break;
			case 12:
				$this->setExternalKey($value);
				break;
			case 13:
				$this->setGuid($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FilePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setHash($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTrackId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setInserted($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setUpdated($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setInputFormat($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setUri($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setSamplef($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setBitrate($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setChannels($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setEncoding($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setSamplebit($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setExternalKey($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setGuid($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FilePeer::DATABASE_NAME);

		if ($this->isColumnModified(FilePeer::ID)) $criteria->add(FilePeer::ID, $this->id);
		if ($this->isColumnModified(FilePeer::HASH)) $criteria->add(FilePeer::HASH, $this->hash);
		if ($this->isColumnModified(FilePeer::TRACK_ID)) $criteria->add(FilePeer::TRACK_ID, $this->track_id);
		if ($this->isColumnModified(FilePeer::INSERTED)) $criteria->add(FilePeer::INSERTED, $this->inserted);
		if ($this->isColumnModified(FilePeer::UPDATED)) $criteria->add(FilePeer::UPDATED, $this->updated);
		if ($this->isColumnModified(FilePeer::INPUT_FORMAT)) $criteria->add(FilePeer::INPUT_FORMAT, $this->input_format);
		if ($this->isColumnModified(FilePeer::URI)) $criteria->add(FilePeer::URI, $this->uri);
		if ($this->isColumnModified(FilePeer::SAMPLEF)) $criteria->add(FilePeer::SAMPLEF, $this->samplef);
		if ($this->isColumnModified(FilePeer::BITRATE)) $criteria->add(FilePeer::BITRATE, $this->bitrate);
		if ($this->isColumnModified(FilePeer::CHANNELS)) $criteria->add(FilePeer::CHANNELS, $this->channels);
		if ($this->isColumnModified(FilePeer::ENCODING)) $criteria->add(FilePeer::ENCODING, $this->encoding);
		if ($this->isColumnModified(FilePeer::SAMPLEBIT)) $criteria->add(FilePeer::SAMPLEBIT, $this->samplebit);
		if ($this->isColumnModified(FilePeer::EXTERNAL_KEY)) $criteria->add(FilePeer::EXTERNAL_KEY, $this->external_key);
		if ($this->isColumnModified(FilePeer::GUID)) $criteria->add(FilePeer::GUID, $this->guid);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FilePeer::DATABASE_NAME);

		$criteria->add(FilePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of File (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setHash($this->hash);

		$copyObj->setTrackId($this->track_id);

		$copyObj->setInserted($this->inserted);

		$copyObj->setUpdated($this->updated);

		$copyObj->setInputFormat($this->input_format);

		$copyObj->setUri($this->uri);

		$copyObj->setSamplef($this->samplef);

		$copyObj->setBitrate($this->bitrate);

		$copyObj->setChannels($this->channels);

		$copyObj->setEncoding($this->encoding);

		$copyObj->setSamplebit($this->samplebit);

		$copyObj->setExternalKey($this->external_key);

		$copyObj->setGuid($this->guid);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCollectionFiles() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCollectionFile($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getFeaturevectors() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFeaturevector($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getFeaturevectorsegments() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFeaturevectorsegment($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     File Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FilePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FilePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Track object.
	 *
	 * @param      Track $v
	 * @return     File The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTrack(Track $v = null)
	{
		if ($v === null) {
			$this->setTrackId(NULL);
		} else {
			$this->setTrackId($v->getId());
		}

		$this->aTrack = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Track object, it will not be re-added.
		if ($v !== null) {
			$v->addFile($this);
		}

		return $this;
	}


	/**
	 * Get the associated Track object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Track The associated Track object.
	 * @throws     PropelException
	 */
	public function getTrack(PropelPDO $con = null)
	{
		if ($this->aTrack === null && ($this->track_id !== null)) {
			$this->aTrack = TrackPeer::retrieveByPk($this->track_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTrack->addFiles($this);
			 */
		}
		return $this->aTrack;
	}

	/**
	 * Clears out the collCollectionFiles collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCollectionFiles()
	 */
	public function clearCollectionFiles()
	{
		$this->collCollectionFiles = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCollectionFiles collection (array).
	 *
	 * By default this just sets the collCollectionFiles collection to an empty array (like clearcollCollectionFiles());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCollectionFiles()
	{
		$this->collCollectionFiles = array();
	}

	/**
	 * Gets an array of CollectionFile objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this File has previously been saved, it will retrieve
	 * related CollectionFiles from storage. If this File is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array CollectionFile[]
	 * @throws     PropelException
	 */
	public function getCollectionFiles($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCollectionFiles === null) {
			if ($this->isNew()) {
			   $this->collCollectionFiles = array();
			} else {

				$criteria->add(CollectionFilePeer::FILE_ID, $this->id);

				CollectionFilePeer::addSelectColumns($criteria);
				$this->collCollectionFiles = CollectionFilePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CollectionFilePeer::FILE_ID, $this->id);

				CollectionFilePeer::addSelectColumns($criteria);
				if (!isset($this->lastCollectionFileCriteria) || !$this->lastCollectionFileCriteria->equals($criteria)) {
					$this->collCollectionFiles = CollectionFilePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCollectionFileCriteria = $criteria;
		return $this->collCollectionFiles;
	}

	/**
	 * Returns the number of related CollectionFile objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related CollectionFile objects.
	 * @throws     PropelException
	 */
	public function countCollectionFiles(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FilePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCollectionFiles === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CollectionFilePeer::FILE_ID, $this->id);

				$count = CollectionFilePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CollectionFilePeer::FILE_ID, $this->id);

				if (!isset($this->lastCollectionFileCriteria) || !$this->lastCollectionFileCriteria->equals($criteria)) {
					$count = CollectionFilePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCollectionFiles);
				}
			} else {
				$count = count($this->collCollectionFiles);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a CollectionFile object to this object
	 * through the CollectionFile foreign key attribute.
	 *
	 * @param      CollectionFile $l CollectionFile
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCollectionFile(CollectionFile $l)
	{
		if ($this->collCollectionFiles === null) {
			$this->initCollectionFiles();
		}
		if (!in_array($l, $this->collCollectionFiles, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCollectionFiles, $l);
			$l->setFile($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this File is new, it will return
	 * an empty collection; or if this File has previously
	 * been saved, it will retrieve related CollectionFiles from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in File.
	 */
	public function getCollectionFilesJoinCollection($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCollectionFiles === null) {
			if ($this->isNew()) {
				$this->collCollectionFiles = array();
			} else {

				$criteria->add(CollectionFilePeer::FILE_ID, $this->id);

				$this->collCollectionFiles = CollectionFilePeer::doSelectJoinCollection($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CollectionFilePeer::FILE_ID, $this->id);

			if (!isset($this->lastCollectionFileCriteria) || !$this->lastCollectionFileCriteria->equals($criteria)) {
				$this->collCollectionFiles = CollectionFilePeer::doSelectJoinCollection($criteria, $con, $join_behavior);
			}
		}
		$this->lastCollectionFileCriteria = $criteria;

		return $this->collCollectionFiles;
	}

	/**
	 * Clears out the collFeaturevectors collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFeaturevectors()
	 */
	public function clearFeaturevectors()
	{
		$this->collFeaturevectors = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFeaturevectors collection (array).
	 *
	 * By default this just sets the collFeaturevectors collection to an empty array (like clearcollFeaturevectors());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFeaturevectors()
	{
		$this->collFeaturevectors = array();
	}

	/**
	 * Gets an array of Featurevector objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this File has previously been saved, it will retrieve
	 * related Featurevectors from storage. If this File is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Featurevector[]
	 * @throws     PropelException
	 */
	public function getFeaturevectors($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFeaturevectors === null) {
			if ($this->isNew()) {
			   $this->collFeaturevectors = array();
			} else {

				$criteria->add(FeaturevectorPeer::FILE_ID, $this->id);

				FeaturevectorPeer::addSelectColumns($criteria);
				$this->collFeaturevectors = FeaturevectorPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FeaturevectorPeer::FILE_ID, $this->id);

				FeaturevectorPeer::addSelectColumns($criteria);
				if (!isset($this->lastFeaturevectorCriteria) || !$this->lastFeaturevectorCriteria->equals($criteria)) {
					$this->collFeaturevectors = FeaturevectorPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFeaturevectorCriteria = $criteria;
		return $this->collFeaturevectors;
	}

	/**
	 * Returns the number of related Featurevector objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Featurevector objects.
	 * @throws     PropelException
	 */
	public function countFeaturevectors(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FilePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFeaturevectors === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FeaturevectorPeer::FILE_ID, $this->id);

				$count = FeaturevectorPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FeaturevectorPeer::FILE_ID, $this->id);

				if (!isset($this->lastFeaturevectorCriteria) || !$this->lastFeaturevectorCriteria->equals($criteria)) {
					$count = FeaturevectorPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collFeaturevectors);
				}
			} else {
				$count = count($this->collFeaturevectors);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Featurevector object to this object
	 * through the Featurevector foreign key attribute.
	 *
	 * @param      Featurevector $l Featurevector
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFeaturevector(Featurevector $l)
	{
		if ($this->collFeaturevectors === null) {
			$this->initFeaturevectors();
		}
		if (!in_array($l, $this->collFeaturevectors, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFeaturevectors, $l);
			$l->setFile($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this File is new, it will return
	 * an empty collection; or if this File has previously
	 * been saved, it will retrieve related Featurevectors from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in File.
	 */
	public function getFeaturevectorsJoinTrack($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFeaturevectors === null) {
			if ($this->isNew()) {
				$this->collFeaturevectors = array();
			} else {

				$criteria->add(FeaturevectorPeer::FILE_ID, $this->id);

				$this->collFeaturevectors = FeaturevectorPeer::doSelectJoinTrack($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FeaturevectorPeer::FILE_ID, $this->id);

			if (!isset($this->lastFeaturevectorCriteria) || !$this->lastFeaturevectorCriteria->equals($criteria)) {
				$this->collFeaturevectors = FeaturevectorPeer::doSelectJoinTrack($criteria, $con, $join_behavior);
			}
		}
		$this->lastFeaturevectorCriteria = $criteria;

		return $this->collFeaturevectors;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this File is new, it will return
	 * an empty collection; or if this File has previously
	 * been saved, it will retrieve related Featurevectors from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in File.
	 */
	public function getFeaturevectorsJoinFeaturevectortype($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFeaturevectors === null) {
			if ($this->isNew()) {
				$this->collFeaturevectors = array();
			} else {

				$criteria->add(FeaturevectorPeer::FILE_ID, $this->id);

				$this->collFeaturevectors = FeaturevectorPeer::doSelectJoinFeaturevectortype($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FeaturevectorPeer::FILE_ID, $this->id);

			if (!isset($this->lastFeaturevectorCriteria) || !$this->lastFeaturevectorCriteria->equals($criteria)) {
				$this->collFeaturevectors = FeaturevectorPeer::doSelectJoinFeaturevectortype($criteria, $con, $join_behavior);
			}
		}
		$this->lastFeaturevectorCriteria = $criteria;

		return $this->collFeaturevectors;
	}

	/**
	 * Clears out the collFeaturevectorsegments collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFeaturevectorsegments()
	 */
	public function clearFeaturevectorsegments()
	{
		$this->collFeaturevectorsegments = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFeaturevectorsegments collection (array).
	 *
	 * By default this just sets the collFeaturevectorsegments collection to an empty array (like clearcollFeaturevectorsegments());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFeaturevectorsegments()
	{
		$this->collFeaturevectorsegments = array();
	}

	/**
	 * Gets an array of Featurevectorsegment objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this File has previously been saved, it will retrieve
	 * related Featurevectorsegments from storage. If this File is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Featurevectorsegment[]
	 * @throws     PropelException
	 */
	public function getFeaturevectorsegments($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFeaturevectorsegments === null) {
			if ($this->isNew()) {
			   $this->collFeaturevectorsegments = array();
			} else {

				$criteria->add(FeaturevectorsegmentPeer::FILE_ID, $this->id);

				FeaturevectorsegmentPeer::addSelectColumns($criteria);
				$this->collFeaturevectorsegments = FeaturevectorsegmentPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FeaturevectorsegmentPeer::FILE_ID, $this->id);

				FeaturevectorsegmentPeer::addSelectColumns($criteria);
				if (!isset($this->lastFeaturevectorsegmentCriteria) || !$this->lastFeaturevectorsegmentCriteria->equals($criteria)) {
					$this->collFeaturevectorsegments = FeaturevectorsegmentPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFeaturevectorsegmentCriteria = $criteria;
		return $this->collFeaturevectorsegments;
	}

	/**
	 * Returns the number of related Featurevectorsegment objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Featurevectorsegment objects.
	 * @throws     PropelException
	 */
	public function countFeaturevectorsegments(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FilePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFeaturevectorsegments === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FeaturevectorsegmentPeer::FILE_ID, $this->id);

				$count = FeaturevectorsegmentPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FeaturevectorsegmentPeer::FILE_ID, $this->id);

				if (!isset($this->lastFeaturevectorsegmentCriteria) || !$this->lastFeaturevectorsegmentCriteria->equals($criteria)) {
					$count = FeaturevectorsegmentPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collFeaturevectorsegments);
				}
			} else {
				$count = count($this->collFeaturevectorsegments);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Featurevectorsegment object to this object
	 * through the Featurevectorsegment foreign key attribute.
	 *
	 * @param      Featurevectorsegment $l Featurevectorsegment
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFeaturevectorsegment(Featurevectorsegment $l)
	{
		if ($this->collFeaturevectorsegments === null) {
			$this->initFeaturevectorsegments();
		}
		if (!in_array($l, $this->collFeaturevectorsegments, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFeaturevectorsegments, $l);
			$l->setFile($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this File is new, it will return
	 * an empty collection; or if this File has previously
	 * been saved, it will retrieve related Featurevectorsegments from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in File.
	 */
	public function getFeaturevectorsegmentsJoinFeaturevector($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFeaturevectorsegments === null) {
			if ($this->isNew()) {
				$this->collFeaturevectorsegments = array();
			} else {

				$criteria->add(FeaturevectorsegmentPeer::FILE_ID, $this->id);

				$this->collFeaturevectorsegments = FeaturevectorsegmentPeer::doSelectJoinFeaturevector($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FeaturevectorsegmentPeer::FILE_ID, $this->id);

			if (!isset($this->lastFeaturevectorsegmentCriteria) || !$this->lastFeaturevectorsegmentCriteria->equals($criteria)) {
				$this->collFeaturevectorsegments = FeaturevectorsegmentPeer::doSelectJoinFeaturevector($criteria, $con, $join_behavior);
			}
		}
		$this->lastFeaturevectorsegmentCriteria = $criteria;

		return $this->collFeaturevectorsegments;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCollectionFiles) {
				foreach ((array) $this->collCollectionFiles as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collFeaturevectors) {
				foreach ((array) $this->collFeaturevectors as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collFeaturevectorsegments) {
				foreach ((array) $this->collFeaturevectorsegments as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCollectionFiles = null;
		$this->collFeaturevectors = null;
		$this->collFeaturevectorsegments = null;
			$this->aTrack = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseFile:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseFile::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseFile
