<?php


/**
 * This class defines the structure of the 'collection_file' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 30 15:27:44 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.smafe.map
 */
class CollectionFileTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.smafe.map.CollectionFileTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('collection_file');
		$this->setPhpName('CollectionFile');
		$this->setClassname('CollectionFile');
		$this->setPackage('lib.model.smafe');
		$this->setUseIdGenerator(false);
		// columns
		$this->addForeignPrimaryKey('COLLECTION_ID', 'CollectionId', 'INTEGER' , 'collection', 'ID', true, null, null);
		$this->addForeignPrimaryKey('FILE_ID', 'FileId', 'INTEGER' , 'file', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Collection', 'Collection', RelationMap::MANY_TO_ONE, array('collection_id' => 'id', ), null, 'CASCADE');
    $this->addRelation('File', 'File', RelationMap::MANY_TO_ONE, array('file_id' => 'id', ), null, 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // CollectionFileTableMap
