<?php


/**
 * This class defines the structure of the 'smafejob_deletecollection' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 30 15:27:45 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.smafe.map
 */
class SmafejobDeletecollectionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.smafe.map.SmafejobDeletecollectionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('smafejob_deletecollection');
		$this->setPhpName('SmafejobDeletecollection');
		$this->setClassname('SmafejobDeletecollection');
		$this->setPackage('lib.model.smafe');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('smafejob_deletecollection_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('PRIORITY', 'Priority', 'INTEGER', true, null, 0);
		$this->addColumn('COLLECTION_NAME', 'CollectionName', 'VARCHAR', true, 255, null);
		$this->addColumn('CREATED', 'Created', 'TIMESTAMP', true, null, 'now()');
		$this->addColumn('STARTED', 'Started', 'TIMESTAMP', false, null, null);
		$this->addColumn('FINISHED1', 'Finished1', 'TIMESTAMP', false, null, null);
		$this->addColumn('STARTED2', 'Started2', 'TIMESTAMP', false, null, null);
		$this->addColumn('FINISHED2', 'Finished2', 'TIMESTAMP', false, null, null);
		$this->addColumn('FINISHED', 'Finished', 'TIMESTAMP', false, null, null);
		$this->addColumn('STATUS', 'Status', 'VARCHAR', false, 255, null);
		$this->addColumn('LOG', 'Log', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SmafejobDeletecollectionTableMap
