<?php


/**
 * This class defines the structure of the 'track' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 30 15:27:45 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.smafe.map
 */
class TrackTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.smafe.map.TrackTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('track');
		$this->setPhpName('Track');
		$this->setClassname('Track');
		$this->setPackage('lib.model.smafe');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('track_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('FINGERPRINT', 'Fingerprint', 'VARCHAR', false, 255, null);
		$this->addColumn('INSERTED', 'Inserted', 'TIMESTAMP', false, -4, null);
		$this->addColumn('UPDATED', 'Updated', 'TIMESTAMP', false, -4, null);
		$this->addColumn('MBID', 'Mbid', 'INTEGER', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Featurevector', 'Featurevector', RelationMap::ONE_TO_MANY, array('id' => 'track_id', ), 'RESTRICT', 'CASCADE');
    $this->addRelation('File', 'File', RelationMap::ONE_TO_MANY, array('id' => 'track_id', ), 'RESTRICT', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TrackTableMap
